http://www.bogotobogo.com/python/python_numpy_batch_gradient_descent_algorithm.php

In [2]:
import numpy as np
import random
from sklearn.datasets.samples_generator import make_regression 
import pylab
from scipy import stats

In [28]:
def gradient_descent_2(alpha, x, y, numIterations):
    m = x.shape[0] # number of samples
    theta = np.ones(2)
    x_transpose = x.transpose()
    for iter in range(0, numIterations):
        hypothesis = np.dot(x, theta)
        loss = hypothesis - y
        J = np.sum(loss ** 2) / (2 * m)  # cost    
        gradient = np.dot(x_transpose, loss) / m         
        theta = theta - alpha * gradient  # update
    return theta

In [29]:
x,y = make_regression(n_samples=100, n_features=1, n_informative=1, random_state=0, noise = 35)

In [30]:
m, n = np.shape(x)

In [31]:
x = np.c_[np.ones(m), x]

In [32]:
alpha = 0.01

In [34]:
#theta = gradient_descent(alpha, x, y, 1000)

In [35]:
theta

array([ 0.00241583, -0.44323826])

In [9]:
for i in range(x.shape[1]):
    y_predict = theta[0] + theta[1]*x
pylab.plot(x[:,1], y, 'o')
pylab.plot(x,y_predict, 'k-')
pylab.show()

# Trying to Modify with Multiple Features

In [40]:
x,y = make_regression(n_samples=10000, n_features=10, n_informative=1, random_state=0, noise = 35)
m, n = np.shape(x)
x = np.c_[np.ones(m), x]

In [50]:
def gradient_descent_2(alpha, x, y, numIterations):
    m = x.shape[0] # number of samples
    theta = np.ones(x.shape[1])
    x_transpose = x.transpose()
    for iter in range(0, numIterations):
        hypothesis = np.dot(x, theta)
        loss = hypothesis - y
        J = np.sum(loss ** 2) / (2 * m)  # cost    
        gradient = np.dot(x_transpose, loss) / m         
        theta = theta - alpha * gradient  # update
    return theta

In [52]:
theta = gradient_descent_2(alpha, x, y, 5000)

In [53]:
theta

array([  1.61442711e-01,   2.31521560e-01,  -4.56942585e-01,
        -4.27325681e-01,   5.59132621e-01,  -6.25289551e-02,
         4.63817731e-01,   5.35680984e-03,   7.90696645e+01,
         3.07219266e-01,   1.19193699e-01])

## Compare to Stats Models

In [54]:
import statsmodels.api as sm

In [55]:
X = sm.add_constant(x)

In [57]:
model = sm.OLS(y, X).fit()

In [58]:
model.params

array([  1.61442711e-01,   2.31521560e-01,  -4.56942585e-01,
        -4.27325681e-01,   5.59132621e-01,  -6.25289551e-02,
         4.63817731e-01,   5.35680984e-03,   7.90696645e+01,
         3.07219266e-01,   1.19193699e-01])